import"../../app/globals.css";
// import {useContextProvider as UseContextProvider} from "@/context/context";
import { contextProvider as ContextProvider } from "../../context/context";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <ContextProvider>
      <body>{children}</body>
      </ContextProvider>
    </html>
  )
}
